"""Per-stage sub-region wrappers for bundled composite icons.

These are *manually defined* — they are NOT regenerated by
`scripts/sanitize_bioicons.py`. Each entry is a thin `<symbol>` whose
viewBox crops a region of a larger composite, and whose body just
`<use>`s that composite. Lazy-injection's transitive `<use>` resolution
(see `_resolve_transitive_refs` in `app/tools/vector_schematic.py`)
pulls the composite into `<defs>` whenever any of these wrappers is
referenced.

Why wrappers instead of duplicating path data?
- Each wrapper is ~150 bytes vs ~43 KB for the composite body.
- Bytes are paid once for the composite + a few hundred extra per
  variant. Duplication would mean N × 43 KB.

Why bother decomposing at all?
- Round 2's pilot live test surfaced a structural limitation: when the
  LLM uses a single composite icon and tries to overlay N stage labels,
  it guesses the internal pixel positions and gets them wrong. The
  per-stage decomposition lets the LLM place one icon per stage and put
  the label directly next to its `<use>` — the same pattern that gave
  clean output on the fertilisation prompt (`bioicons_zygote` +
  `bioicons_embryo_2cell` each had their own icon).

Stage selection for `bioicons_mitosis`:
The Servier mitosis composite contains 7 visual scenes arranged
non-linearly. We expose 5 of those as the conventional textbook stages.
The bounding boxes were identified visually from a high-resolution
render with a coordinate-grid overlay (see /tmp/mitosis_with_grid.png).
"""

from __future__ import annotations


def _wrap(slug: str, parent_id: str, parent_w: float, parent_h: float,
          crop: tuple[float, float, float, float]) -> str:
    x, y, w, h = crop
    return (
        f'<symbol id="{slug}" viewBox="{x} {y} {w} {h}">'
        f'<use href="#{parent_id}" x="0" y="0" '
        f'width="{parent_w}" height="{parent_h}"/>'
        f"</symbol>"
    )


# Servier "Mitosis.svg" composite viewBox is 0 0 380.787 441.411.
# Each sub-region is a generous bounding box around one stage's oval.
BIOICONS_SUBREGIONS: dict[str, str] = {
    # Middle-left oval — chromatin still diffuse, nuclear envelope intact,
    # no individual chromosomes resolved. INTERPHASE.
    "bioicons_mitosis_interphase": _wrap(
        "bioicons_mitosis_interphase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(0, 110, 165, 110),
    ),
    # Top-center oval — chromatin condensed into a tight magenta cluster,
    # nuclear envelope still intact. PROPHASE.
    "bioicons_mitosis_prophase": _wrap(
        "bioicons_mitosis_prophase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(120, 0, 145, 105),
    ),
    # Middle-right oval — distinct condensed chromosomes scattered inside,
    # nuclear envelope dissolved. PROMETAPHASE.
    "bioicons_mitosis_prometaphase": _wrap(
        "bioicons_mitosis_prometaphase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(215, 120, 160, 110),
    ),
    # Bottom-right oval — full bipolar spindle with chromosomes aligned at
    # the metaphase plate. METAPHASE.
    "bioicons_mitosis_metaphase": _wrap(
        "bioicons_mitosis_metaphase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(225, 240, 160, 105),
    ),
    # Bottom-left-1 small oval — chromosomes scattered, transitioning from
    # the metaphase plate toward opposite poles. ANAPHASE. Round 11 dogfood
    # exposed this gap (LLM was hand-drawing anaphase from primitives).
    "bioicons_mitosis_anaphase": _wrap(
        "bioicons_mitosis_anaphase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(5, 245, 125, 95),
    ),
    # Bottom figure-8 oval — cleavage furrow nearly complete, chromosomes
    # at opposite poles. TELOPHASE / cytokinesis.
    "bioicons_mitosis_telophase": _wrap(
        "bioicons_mitosis_telophase",
        parent_id="bioicons_mitosis", parent_w=380.787, parent_h=441.411,
        crop=(110, 345, 175, 110),
    ),
    # ── Meiosis stage crops (parent: bioicons_meiosis, viewBox 0 0 573.808 347.376) ──
    # Servier's meiosis composite has 8 ovals arranged left→right:
    #   • 2 big ovals (left column): Meiosis I prophase & metaphase
    #   • 2 medium ovals (centre column, stacked): late Meiosis I / early Meiosis II
    #   • 4 small ovals (right column, stacked): Meiosis II progression
    # Boundaries identified visually from /tmp/meiosis_clean.png. Labels follow
    # the standard textbook 8-stage scheme; some stage assignments are
    # approximate because Servier's diagram compresses anaphase into the
    # adjacent telophase scenes.
    "bioicons_meiosis_prophase_i": _wrap(
        "bioicons_meiosis_prophase_i",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(10, 80, 190, 195),
    ),
    "bioicons_meiosis_metaphase_i": _wrap(
        "bioicons_meiosis_metaphase_i",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(220, 80, 165, 195),
    ),
    "bioicons_meiosis_anaphase_i": _wrap(
        "bioicons_meiosis_anaphase_i",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(290, 75, 135, 125),
    ),
    "bioicons_meiosis_telophase_i": _wrap(
        "bioicons_meiosis_telophase_i",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(290, 200, 135, 130),
    ),
    "bioicons_meiosis_prophase_ii": _wrap(
        "bioicons_meiosis_prophase_ii",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(470, 65, 95, 85),
    ),
    "bioicons_meiosis_metaphase_ii": _wrap(
        "bioicons_meiosis_metaphase_ii",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(470, 145, 95, 80),
    ),
    "bioicons_meiosis_anaphase_ii": _wrap(
        "bioicons_meiosis_anaphase_ii",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(470, 215, 95, 75),
    ),
    "bioicons_meiosis_telophase_ii": _wrap(
        "bioicons_meiosis_telophase_ii",
        parent_id="bioicons_meiosis", parent_w=573.808, parent_h=347.376,
        crop=(470, 275, 95, 75),
    ),
}
