"""
Analysis: Path D generated-icon probe — cross-icon consistency, background
          removability, and embed size.
Date: 2026-06-01
Related progress log: docs/progress/260601_path_d_mixed_vector_raster.md

Problem:
    Path D draws every biological entity in a figure as an INDEPENDENTLY
    generated Gemini raster icon (no library mixing), embedded into a vector
    backbone. Three things must hold for the design to be viable:

    H59 (consistency) — icons generated by SEPARATE image calls, all using the
        single fixed ICON_STYLE_PREFIX (app/agent/prompts/gen_icon.py), must
        look like ONE coherent family within a figure (palette, line weight,
        lighting). This is the headline risk: drift makes the figure look
        patchworked.
    H60 (bg removal) — the solid-white background must strip cleanly into a
        transparent PNG with no halo fringe on a non-white composite and no
        internal-white punch-through. This probe uses THRESHOLD removal
        (Pillow only; rembg not installed). Bad fringe here is evidence FOR
        pulling in rembg/U2Net.
    H62 (size) — per-icon raster + base64 data-uri size, to judge the
        resolution/embed-size knee for SVG bloat.

    Note: the icon image model is expected to return JPEG (same as Path C).
    JPEG edge artifacts mean the "white" bg is not a pure 255 → threshold
    removal will likely leave some fringe. That degradation is itself a
    finding relevant to H60 (argues for rembg, or for requesting PNG).

Judgment Criteria:
    H59 consistency (eyeball the contact sheet) — do the 6 icons read as one
        set? Score CONSISTENT / MINOR-DRIFT / PATCHWORK.
        - CONSISTENT  → fixed prefix is enough; proceed with single-call-per-icon.
        - MINOR-DRIFT → acceptable; note which axis drifts (color vs line).
        - PATCHWORK   → fixed prefix insufficient; fallback to image-to-image
                        conditioning (generate icon-1, condition the rest).
    H60 bg removal (eyeball icons composited on mid-gray) — CLEAN / FRINGE /
        BROKEN (internal holes). FRINGE/BROKEN → rembg needed.
    H62 size — report bytes + data-uri chars per icon. Flag if a single icon's
        data-uri exceeds ~200 KB (SVG bloat concern).

    Overall: ADOPT (single-call viable) / ADOPT-WITH-REMBG / NEEDS-FALLBACK
    (image-to-image conditioning) / REJECT.

Conclusion (2026-06-01, 6 icons, gemini-3.1-flash-image-preview, 97s, all JPEG):
    H59 CONSISTENT → ADOPT. Six morphologically diverse entities, six SEPARATE
        image calls, single fixed prefix → read as one coherent family: same
        dark-outline weight, same flat pastel palette (cool blues/purples/
        teals), same flat shading. Fixed prefix is SUFFICIENT; image-to-image
        conditioning fallback NOT needed. Minor note: palette skews cool —
        coherent, but low hue variety.
    H60 CLEAN with threshold → ADOPT WITHOUT rembg. Pure-Pillow white-threshold
        (>240) removal leaves no visible halo on mid-gray and no internal
        punch-through. Reason: the prefix-mandated "clean dark outlines" put
        the cell boundary on a dark line, so little antialiased white bleed at
        the edge. Style rule and bg-removability reinforce each other. The
        heavy rembg/onnxruntime dep is NOT required → Step 7 satisfied by
        threshold.
    H62 FAIL as-is → fixed by post-process. Raw embed is 578-923 KB/icon
        (1408x768 landscape, ~55-80% white margin, lossless PNG of shaded art).
        Resolved in [[analyze/260601_path_d_icon_postprocess_size.py]]:
        crop-to-alpha-bbox + downscale(320px) + quantize(64) → 23-84 KB/icon,
        ~347 KB for a 6-icon figure. ACCEPTABLE.

    OVERALL: ADOPT. Single-call-per-icon + threshold bg-removal + size
    post-process. No rembg, no image-to-image fallback. Proceed to implement.

Usage:
    uv run python analyze/260601_path_d_icon_consistency_probe.py
"""

from __future__ import annotations

import asyncio
import base64
import json
import sys
import time
from io import BytesIO
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(ROOT / ".env", override=True)

from PIL import Image  # noqa: E402

from app.agent.prompts.gen_icon import ICON_STYLE_PREFIX  # noqa: E402
from app.clients.gemini import GeminiClient  # noqa: E402
from app.tools.raster_illustration import detect_image_mime  # noqa: E402

# One coherent figure's worth of entities, deliberately diverse in morphology
# so consistency is genuinely stressed (round cell vs spiky vs spindle vs
# cluster). All share the SAME style prefix — that is the H59 test.
ENTITIES: list[tuple[str, str]] = [
    ("monocyte", "a monocyte immune cell with a kidney-shaped nucleus"),
    ("m1_macrophage", "an M1 macrophage immune cell, amoeboid with small surface protrusions"),
    ("dendritic_cell", "a dendritic immune cell with multiple long spiky dendrites"),
    ("cd8_tcell", "a CD8 positive cytotoxic T cell, round and smooth with a darker nucleus"),
    ("cancer_cluster", "a small cluster of irregular overlapping cancer cells"),
    ("fibroblast", "a spindle-shaped fibroblast cell, elongated"),
]

WHITE_THRESHOLD = 240  # R,G,B all above this → treated as background → alpha 0


def threshold_remove_bg(data: bytes) -> Image.Image:
    """Make near-white pixels transparent. Pure-Pillow threshold removal.

    Returns an RGBA image. Crude on purpose — exposes JPEG fringe so H60 is
    judged honestly against the cheap method before committing to rembg.
    """
    img = Image.open(BytesIO(data)).convert("RGBA")
    px = img.getdata()
    out = [
        (r, g, b, 0) if (r >= WHITE_THRESHOLD and g >= WHITE_THRESHOLD and b >= WHITE_THRESHOLD)
        else (r, g, b, a)
        for (r, g, b, a) in px
    ]
    img.putdata(out)
    return img


def composite_on(img_rgba: Image.Image, bg: tuple[int, int, int]) -> Image.Image:
    canvas = Image.new("RGBA", img_rgba.size, bg + (255,))
    canvas.alpha_composite(img_rgba)
    return canvas.convert("RGB")


def build_contact_sheet(
    cells: list[tuple[str, Image.Image, Image.Image]],
    thumb: int = 256,
) -> Image.Image:
    """Two rows per icon column: top = on white, bottom = on mid-gray.

    Eyeballing the white row tests H59 (do they match as a set);
    the gray row tests H60 (fringe / halo on a non-white composite).
    """
    n = len(cells)
    pad = 12
    sheet_w = n * thumb + (n + 1) * pad
    sheet_h = 2 * thumb + 3 * pad
    sheet = Image.new("RGB", (sheet_w, sheet_h), (255, 255, 255))
    for i, (_, on_white, on_gray) in enumerate(cells):
        x = pad + i * (thumb + pad)
        w = on_white.copy(); w.thumbnail((thumb, thumb))
        g = on_gray.copy(); g.thumbnail((thumb, thumb))
        sheet.paste(w, (x, pad))
        sheet.paste(g, (x, 2 * pad + thumb))
    return sheet


async def main() -> None:
    print("=" * 70)
    print("[probe] Path D generated-icon consistency / bg-removal / size probe")
    print(f"[probe] entities: {len(ENTITIES)} (one figure's worth)")
    print(f"[probe] style prefix: {len(ICON_STYLE_PREFIX)} chars")
    print("=" * 70)

    client = GeminiClient()
    out_dir = Path("/tmp/path_d_probe")
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d_%H%M%S")

    cells: list[tuple[str, Image.Image, Image.Image]] = []
    records: list[dict] = []

    t_all = time.time()
    for slug, desc in ENTITIES:
        prompt = f"{ICON_STYLE_PREFIX}{desc}"
        t0 = time.time()
        try:
            raw = await client.generate_image(prompt)
        except Exception as exc:
            print(f"[probe] {slug}: FAILED {type(exc).__name__}: {exc}")
            raise
        elapsed = time.time() - t0

        mime = detect_image_mime(raw)
        src = Image.open(BytesIO(raw))
        dims = src.size

        rgba = threshold_remove_bg(raw)
        n_transparent = sum(1 for p in rgba.getdata() if p[3] == 0)
        transparent_pct = 100.0 * n_transparent / (dims[0] * dims[1])

        # transparent PNG (what Path D would embed) + composites for eyeballing
        png_buf = BytesIO()
        rgba.save(png_buf, format="PNG")
        png_bytes = png_buf.getvalue()
        data_uri_len = len(base64.b64encode(png_bytes))

        on_white = composite_on(rgba, (255, 255, 255))
        on_gray = composite_on(rgba, (150, 150, 150))
        cells.append((slug, on_white, on_gray))

        (out_dir / f"{slug}_raw").with_suffix(".jpg" if "jpeg" in mime else ".png").write_bytes(raw)
        (out_dir / f"{slug}_cut.png").write_bytes(png_bytes)

        rec = {
            "slug": slug,
            "mime": mime,
            "dims": dims,
            "raw_bytes": len(raw),
            "cut_png_bytes": len(png_bytes),
            "data_uri_chars": data_uri_len,
            "transparent_pct": round(transparent_pct, 1),
            "gen_seconds": round(elapsed, 2),
        }
        records.append(rec)
        print(
            f"[probe] {slug:16s} {mime:11s} {dims[0]}x{dims[1]} "
            f"raw={len(raw)//1024}KB cut={len(png_bytes)//1024}KB "
            f"uri={data_uri_len//1024}KB transp={transparent_pct:4.1f}% "
            f"{elapsed:4.1f}s"
        )

    sheet = build_contact_sheet(cells)
    sheet_path = out_dir / f"contact_sheet_{ts}.png"
    sheet.save(sheet_path)
    Image.open(sheet_path).save(out_dir / "contact_sheet_latest.png")

    meta = {
        "timestamp": ts,
        "icon_model": client._image_model,  # noqa: SLF001  (probe introspection)
        "style_prefix_chars": len(ICON_STYLE_PREFIX),
        "white_threshold": WHITE_THRESHOLD,
        "total_seconds": round(time.time() - t_all, 2),
        "icons": records,
    }
    (out_dir / f"meta_{ts}.json").write_text(json.dumps(meta, indent=2))

    print("-" * 70)
    print(f"[probe] contact sheet: {sheet_path}")
    print(f"[probe]   (top row = on white  → H59 consistency)")
    print(f"[probe]   (bottom row = on gray → H60 fringe/halo)")
    print(f"[probe] cut PNGs + raw in: {out_dir}")
    print(f"[probe] total: {meta['total_seconds']}s")
    print()
    print("JUDGE:")
    print("  H59  open contact_sheet — top row read as one family? "
          "CONSISTENT / MINOR-DRIFT / PATCHWORK")
    print("  H60  bottom (gray) row — halo fringe or internal holes? "
          "CLEAN / FRINGE / BROKEN")
    print("  H62  data_uri_chars above — any icon > ~200KB data-uri?")


if __name__ == "__main__":
    asyncio.run(main())
